[package]
name = "nepali_smart_ime"
version = "1.0.0"
edition = "2021"
authors = ["Elite Systems Architect"]

[dependencies]
# Serde for fast, compact binary serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
# For atomic file writes
tempfile = "3.10"
# For command-line interface styling in the example binary
crossterm = "0.27"
# ADD THIS LINE for the persistence logic
serde_json = "1.0"


[lib]
name = "ime_core"
path = "src/lib.rs"

[[bin]]
name = "ime_engine"
path = "src/bin/main.rs"

# Profile for release build to achieve minimal binary size and max speed
[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Link-Time Optimization
codegen-units = 1   # Slower build, better optimization
panic = 'abort'     # Remove panic unwinding code
strip = true        # Strip debug symbols